name: Publish
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - name: Get version from deno.json
        uses: polyseam/get-version-key-from-json@v1.0.0
        id: get_deno_json
        with:
          path-to-json: "./deno.json"

      - name: Get the tag version without prefix
        id: get_version_from_ref
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_OUTPUT

      - name: Compare Git Tag to CNDI Version
        if: ${{ steps.get_deno_json.outputs.version != steps.get_version_from_ref.outputs.VERSION }}
        run: |
          echo "Deno.json Version: ${{ steps.get_deno_json.outputs.version }} does not match Tag version: ${{ steps.get_version_from_ref.outputs.VERSION }}" && exit 1

      - name: Publish package
        run: npx jsr publish